import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
const host=document.querySelector('#viewport'),loading=document.querySelector('#loading');let dirty=true;
const scene=new THREE.Scene();const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<600?1.25:1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;renderer.shadowMap.enabled=true;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.prepend(renderer.domElement);
const camera=new THREE.PerspectiveCamera(31,1,.01,30);camera.position.set(0,1.64,3.8);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.85,0);controls.minDistance=.23;controls.maxDistance=7;controls.enableDamping=true;controls.addEventListener('change',()=>{dirty=true});controls.maxPolarAngle=Math.PI*.95;
scene.add(new THREE.HemisphereLight(0xf5f0e8,0x607086,1.35));function light(pos,color,power,size){const l=new THREE.DirectionalLight(color,power);l.position.set(...pos);scene.add(l);return l}const key=light([-2,4,3],0xfff1de,1.6);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-1;key.shadow.camera.right=1;key.shadow.camera.top=2;key.shadow.camera.bottom=-1;key.shadow.normalBias=.0025;light([2,2,1],0xd3e4ff,.65);light([0,3,-2],0xffdfb6,1.15);
// Original geometric light room: no downloaded environment image or HDRI.
const room=new THREE.Scene();room.add(new THREE.Mesh(new THREE.SphereGeometry(10,32,16),new THREE.MeshBasicMaterial({color:0x626975,side:THREE.BackSide})));
for(const [pos,scale,value] of [[[-3,3,4],[2,4,.15],[2.2,2.0,1.8]],[[3,2,2],[2,3,.15],[1.2,1.5,1.8]],[[0,4,-3],[3,2,.15],[1.8,1.7,1.5]]]){const panel=new THREE.Mesh(new THREE.BoxGeometry(...scale),new THREE.MeshBasicMaterial({color:new THREE.Color(...value),toneMapped:false}));panel.position.set(...pos);panel.lookAt(0,1,0);room.add(panel)}
const pmrem=new THREE.PMREMGenerator(renderer);const reflection=pmrem.fromScene(room,.06);scene.environment=reflection.texture;scene.environmentIntensity=.35;pmrem.dispose();room.traverse(o=>{o.geometry?.dispose();o.material?.dispose()});
const ground=new THREE.Mesh(new THREE.CircleGeometry(.48,80),new THREE.MeshStandardMaterial({color:0x202934,roughness:1,metalness:0}));ground.rotation.x=-Math.PI/2;ground.position.y=-.012;ground.receiveShadow=true;scene.add(ground);
let model=null,current='',request='',spin=false,wire=false;window.__viewer={ready:false,errors:[]};
async function load(s){const url=s.model+'?v='+s.revision;if(url===current||url===request)return;request=url;loading.hidden=false;loading.textContent='Loading original 3D geometry…';try{const gltf=await new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).loadAsync(url);if(model){scene.remove(model);model.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){const a=Array.isArray(o.material)?o.material:[o.material];a.forEach(m=>{if(m.map)m.map.dispose();m.dispose()})}})}model=gltf.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=false;const mats=Array.isArray(o.material)?o.material:[o.material];o.userData.fineHair=mats.some(m=>/espresso/.test(m.name));o.visible=!(wire&&o.userData.fineHair);for(const m of mats){m.wireframe=wire&&!o.userData.fineHair}}});scene.add(model);current=url;loading.hidden=true;dirty=true;renderer.shadowMap.needsUpdate=true;let meshes=0,triangles=0;model.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3}});window.__viewer={ready:true,meshes,triangles,bounds:new THREE.Box3().setFromObject(model).getSize(new THREE.Vector3()).toArray(),errors:[]}}catch(e){loading.textContent='Model unavailable. Retrying on the next build update.';window.__viewer.errors.push(String(e));console.error(e)}finally{request=''}}
window.addEventListener('model-ready',e=>load(e.detail));fetch('status.json').then(r=>r.json()).then(s=>{if(s.model)load(s)});
function view(mode){spin=false;document.querySelector('#spin').setAttribute('aria-pressed',false);if(mode==='face'){controls.target.set(.045,1.50,0);camera.position.set(.045,1.56,.69)}else{controls.target.set(0,.86,0);if(mode==='back')camera.position.set(0,1.64,-3.8);else if(mode==='threequarter')camera.position.set(2.3,1.65,3.3);else camera.position.set(0,1.64,3.8)}controls.update()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));document.querySelector('#reset').onclick=()=>view('front');document.querySelector('#spin').onclick=e=>{spin=!spin;e.target.setAttribute('aria-pressed',spin)};document.querySelector('#wire').onclick=e=>{wire=!wire;dirty=true;e.target.setAttribute('aria-pressed',wire);model?.traverse(o=>{if(o.isMesh){o.visible=!(wire&&o.userData.fineHair);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.wireframe=wire&&!o.userData.fineHair)}})};
new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();dirty=true}).observe(host);const clock=new THREE.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);controls.autoRotate=spin;controls.autoRotateSpeed=.8;controls.update(dt);if((dirty||spin)&&!document.hidden){renderer.render(scene,camera);dirty=false}});
